// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func gotoUrl(url string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_gotoUrl_e5e9`,
		Function: `function __templ_gotoUrl_e5e9(url){document.location = url;
}`,
		Call:       templ.SafeScript(`__templ_gotoUrl_e5e9`, url),
		CallInline: templ.SafeScriptInline(`__templ_gotoUrl_e5e9`, url),
	}
}

var _ = templruntime.GeneratedTemplate
