// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID          int64
	ArticleSlug string
	UserID      int64
	Body        string
	CreatedAt   pgtype.Timestamptz
	ParentID    pgtype.Int8
	Approved    bool
}

type PageView struct {
	ID          int64
	ArticleSlug string
	IpAddress   string
	UserAgent   string
	CreatedAt   pgtype.Timestamptz
}

type Session struct {
	ID        int64
	UserID    int64
	Token     string
	CsrfToken string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID               int64
	GithubID         int64
	Username         string
	AvatarUrl        string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Email            string
	Unsubscribed     bool
	UnsubscribeToken string
}
