// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID          int64
	ArticleSlug string
	UserID      int64
	Body        string
	CreatedAt   time.Time
	ParentID    sql.NullInt64
	Approved    bool
}

type PageView struct {
	ID          int64
	ArticleSlug string
	IpAddress   string
	UserAgent   string
	CreatedAt   time.Time
}

type Session struct {
	ID        int64
	UserID    int64
	Token     string
	CsrfToken string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID               int64
	GithubID         int64
	Username         string
	AvatarUrl        string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Email            string
	Unsubscribed     bool
	UnsubscribeToken string
}
