// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: page_views.sql

package db

import (
	"context"
)

const countPageViewsBySlug = `-- name: CountPageViewsBySlug :many
SELECT article_slug, count(*)::int AS view_count
FROM page_views
GROUP BY article_slug
ORDER BY view_count DESC
`

type CountPageViewsBySlugRow struct {
	ArticleSlug string
	ViewCount   int32
}

func (q *Queries) CountPageViewsBySlug(ctx context.Context) ([]CountPageViewsBySlugRow, error) {
	rows, err := q.db.Query(ctx, countPageViewsBySlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPageViewsBySlugRow{}
	for rows.Next() {
		var i CountPageViewsBySlugRow
		if err := rows.Scan(&i.ArticleSlug, &i.ViewCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPageView = `-- name: CreatePageView :exec
INSERT INTO page_views (article_slug, ip_address, user_agent)
VALUES ($1, $2, $3)
`

type CreatePageViewParams struct {
	ArticleSlug string
	IpAddress   string
	UserAgent   string
}

func (q *Queries) CreatePageView(ctx context.Context, arg CreatePageViewParams) error {
	_, err := q.db.Exec(ctx, createPageView, arg.ArticleSlug, arg.IpAddress, arg.UserAgent)
	return err
}
